stages:
  prepare:
    cmd: python prepare.py
    deps:
    - fake_data.csv
    - prepare.py
    outs:
    - X.csv
    - y.csv
  train:
    cmd: python train.py
    deps:
    - X.csv
    - prepare.py
    - y.csv
    params:
    - train.random_state
    - train.test_size
    outs:
    - model.pkl
